-- your code goes here

-- 1. Create Table: MEMBER (Superclass)
CREATE TABLE MEMBER (
    MEMBER_ID CHAR(5) PRIMARY KEY,
    NAME VARCHAR(50) NOT NULL,
    EMAIL VARCHAR(50) UNIQUE,
    ADDRESS VARCHAR(100)
);

-- 2. Create Table: STUDENT (Subclass of MEMBER)
CREATE TABLE STUDENT (
    MEMBER_ID CHAR(5) PRIMARY KEY,
    MAX_BOOKS INT CHECK (MAX_BOOKS > 0),
    COURSE VARCHAR(50),
    FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER(MEMBER_ID)
);

-- 3. Create Table: FACULTY (Subclass of MEMBER)
CREATE TABLE FACULTY (
    MEMBER_ID CHAR(5) PRIMARY KEY,
    MAX_BOOKS INT CHECK (MAX_BOOKS > 0),
    DEPARTMENT VARCHAR(50),
    FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER(MEMBER_ID)
);

-- 4. Create Table: BOOK
CREATE TABLE BOOK (
    BOOK_ID CHAR(5) PRIMARY KEY,
    TITLE VARCHAR(100) NOT NULL,
    AUTHOR VARCHAR(50) NOT NULL,
    PUBLISHER VARCHAR(50),
    PRICE DECIMAL(8,2) NOT NULL
);

-- 5. Create Table: BOOK_COPY
CREATE TABLE BOOK_COPY (
    BOOK_ID CHAR(5),
    SERIAL_NO INT,
    STATUS VARCHAR(10) CHECK (STATUS IN ('Available', 'Issued')),
    PRIMARY KEY (BOOK_ID, SERIAL_NO),
    FOREIGN KEY (BOOK_ID) REFERENCES BOOK(BOOK_ID)
);

-- 6. Create Table: TRANSACTION
CREATE TABLE TRANSACTION (
    TRANS_ID CHAR(10) PRIMARY KEY,
    MEMBER_ID CHAR(5) NOT NULL,
    BOOK_ID CHAR(5) NOT NULL,
    SERIAL_NO INT NOT NULL,
    DT_ISSUE DATE DEFAULT CURRENT_DATE,
    TO_BE_RETURNED_BY DATE DEFAULT (CURRENT_DATE + INTERVAL '7' DAY),
    DT_RETURN DATE NULL,
    FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER(MEMBER_ID),
    FOREIGN KEY (BOOK_ID, SERIAL_NO) REFERENCES BOOK_COPY(BOOK_ID, SERIAL_NO)
);

-- Insert Sample Data into MEMBER
INSERT INTO MEMBER VALUES ('M001', 'John Doe', 'john@example.com', '123 Main St');
INSERT INTO MEMBER VALUES ('M002', 'Dr. Smith', 'smith@example.edu', '456 Elm St');
INSERT INTO MEMBER VALUES ('M003', 'Alice Johnson', 'alice@example.com', '789 Pine St');

-- Insert Sample Data into STUDENT (Subclass of MEMBER)
INSERT INTO STUDENT VALUES ('M001', 3, 'Computer Science');
INSERT INTO STUDENT VALUES ('M003', 3, 'Mathematics');

-- Insert Sample Data into FACULTY (Subclass of MEMBER)
INSERT INTO FACULTY VALUES ('M002', 5, 'Physics Department');

-- Insert Sample Data into BOOK table
INSERT INTO BOOK VALUES ('B001', 'The Great Gatsby', 'F. Scott Fitzgerald', 'Scribner', 399.99);
INSERT INTO BOOK VALUES ('B002', '1984', 'George Orwell', 'Penguin', 499.50);
INSERT INTO BOOK VALUES ('B003', 'To Kill a Mockingbird', 'Harper Lee', 'J.B. Lippincott', 299.75);

-- Insert Sample Data into BOOK_COPY table
INSERT INTO BOOK_COPY VALUES ('B001', 1, 'Available');
INSERT INTO BOOK_COPY VALUES ('B001', 2, 'Available');
INSERT INTO BOOK_COPY VALUES ('B002', 1, 'Available');
INSERT INTO BOOK_COPY VALUES ('B002', 2, 'Available');
INSERT INTO BOOK_COPY VALUES ('B003', 1, 'Available');

-- Issue a Book (Insert into TRANSACTION and update BOOK_COPY)
INSERT INTO TRANSACTION (TRANS_ID, MEMBER_ID, BOOK_ID, SERIAL_NO, DT_ISSUE, TO_BE_RETURNED_BY)
VALUES ('T1001', 'M001', 'B001', 1, CURRENT_DATE, CURRENT_DATE + INTERVAL '7' DAY);

UPDATE BOOK_COPY SET STATUS = 'Issued' WHERE BOOK_ID = 'B001' AND SERIAL_NO = 1;

-- Another Book Issue
INSERT INTO TRANSACTION (TRANS_ID, MEMBER_ID, BOOK_ID, SERIAL_NO, DT_ISSUE, TO_BE_RETURNED_BY)
VALUES ('T1002', 'M002', 'B002', 2, CURRENT_DATE, CURRENT_DATE + INTERVAL '7' DAY);

UPDATE BOOK_COPY SET STATUS = 'Issued' WHERE BOOK_ID = 'B002' AND SERIAL_NO = 2;

-- Return Book (Update TRANSACTION and BOOK_COPY)
UPDATE TRANSACTION 
SET DT_RETURN = CURRENT_DATE 
WHERE TRANS_ID = 'T1001';

UPDATE BOOK_COPY 
SET STATUS = 'Available' 
WHERE BOOK_ID = 'B001' AND SERIAL_NO = 1;

-- Check all books
SELECT * FROM BOOK;
SELECT * FROM BOOK_COPY;
SELECT * FROM MEMBER;
SELECT * FROM STUDENT;
SELECT * FROM FACULTY;
SELECT * FROM TRANSACTION;
